export const CATEGORIES = [
  { id: "swallows", name: "Swallows", icon: "🥣" },
  { id: "rice-dishes", name: "Rice Dishes", icon: "🍚" },
  { id: "local-staples", name: "Local Staples", icon: "🍃" },
  { id: "seafood-grills", name: "Seafood & Grills", icon: "🦀" },
];

export const FOOD_DATA = [
  // --- SEAFOOD & GRILLS ---
  {
    id: 1,
    title: "Banku with Tilapia",
    price: "GHC 180",
    category: "seafood-grills",
    desc: "Freshly grilled river tilapia paired with hot, soft banku, served alongside rich shito and freshly ground green pepper.",
    img: "/banku with tilapia.jfif",
    btn: "Order Now",
  },
  {
    id: 2,
    title: "Boutique Garlic Crab Platter",
    price: "GHC 280",
    category: "seafood-grills",
    desc: "Jumbo local mud crabs sautéed in a rich, spicy garlic-butter sauce, served with fried yam chips.",
    img: "/Boutique Garlic Crab Platter.jfif",
    btn: "Order Now",
  },
  {
    id: 3,
    title: "Grilled Spicy Prawns",
    price: "GHC 160",
    category: "seafood-grills",
    desc: "Skewered tiger prawns marinated in local spices and flame-grilled to perfection, served with kelewele.",
    img: "/Grilled Spicy Prawns.jfif",
    btn: "Order Now",
  },
  {
    id: 4,
    title: "Charcoal Grilled Catfish",
    price: "GHC 190",
    category: "seafood-grills",
    desc: "Slow-cooked over hot coals, glazed with a spicy house marinade, served with fresh pepper and onions.",
    img: "/Charcoal Grilled Catfish.jfif",
    btn: "Order Now",
  },

  // --- RICE DISHES ---
  {
    id: 5,
    title: "Premium Jollof Rice",
    price: "GHC 150",
    category: "rice-dishes",
    desc: "Smoky, authentic Ghanaian Jollof rice served with grilled chicken, sweet fried plantains (kelewele), and a side salad.",
    img: "/Premium Jollof Rice.jfif",
    btn: "Order Now",
  },
  {
    id: 6,
    title: "Seafood Jollof Rice",
    price: "GHC 210",
    category: "rice-dishes",
    desc: "Our signature smoky jollof loaded with chopped crab meat, prawns, and calamari.",
    img: "/Seafood Jollof Rice.jfif",
    btn: "Order Now",
  },
  {
    id: 7,
    title: "Angwamo (Tolo Beef Fried Rice)",
    price: "GHC 120",
    category: "rice-dishes",
    desc: "Traditional coconut-oil scented rice fried with authentic salted beef (tolo beef), served with fried eggs and hot pepper.",
    img: "/Premium Jollof Rice.jfif",
    btn: "Order Now",
  },
  {
    id: 8,
    title: "Fried Rice with Crispy Fish",
    price: "GHC 140",
    category: "rice-dishes",
    desc: "Local style stir-fried seasoned rice served with a golden, crispy deep-fried red fish platter.",
    img: "/oil rice.jfif",
    btn: "Order Now",
  },

  // --- SWALLOWS ---
  {
    id: 9,
    title: "Fufu with Goat Light Soup",
    price: "GHC 200",
    category: "swallows",
    desc: "Pounded cassava and plantain fufu swimming in a deeply seasoned, fiery local goat light soup.",
    img: "/Fufu with Goat Light Soup.jfif",
    btn: "Order Now",
  },
  {
    id: 10,
    title: "Seafood Okro Soup with TZ",
    price: "GHC 220",
    category: "swallows",
    desc: "Smooth Tuo Zaafi paired with a premium, crunchy okro stew packed with crabs, wele, and fresh fish.",
    img: "/Seafood Okro Soup with TZ.jfif",
    btn: "Order Now",
  },
  {
    id: 11,
    title: "Eba with Egusi & Crab Stew",
    price: "GHC 180",
    category: "swallows",
    desc: "Sour, steaming hot pan-rolled eba served with rich melon-seed egusi stew, loaded with local crabs.",
    img: "/Eba with Egusi & Crab Stew.jfif",
    btn: "Order Now",
  },
  {
    id: 12,
    title: "Fufu with Palm Nut Soup (Abenkwan)",
    price: "GHC 190",
    category: "swallows",
    desc: "Silky fufu served with thick, rich palm fruit soup cooked with assorted smoked fish and beef triangles.",
    img: "/Fufu with Palm Nut Soup (Abenkwan).jfif",
    btn: "Order Now",
  },

  // --- LOCAL STAPLES ---
  {
    id: 13,
    title: "Boutique Leaf Waakye Platter",
    price: "GHC 160",
    category: "local-staples",
    desc: "Classic rice and beans cooked in katemfe leaves, loaded with wele, talia, gari, avocado, egg, and rich shito.",
    img: "/Boutique Leaf Waakye Platter.jfif",
    btn: "Order Now",
  },
  {
    id: 14,
    title: "Gari Foto with Grilled Prawns",
    price: "GHC 140",
    category: "local-staples",
    desc: "Dampened gari tossed in a rich, seasoned tomato and vegetable sauce, elevated with premium grilled prawns.",
    img: "/Gari Foto with Grilled Prawns.jpg",
    btn: "Order Now",
  },
  {
    id: 15,
    title: "Red Red (Gob3 Supreme)",
    price: "GHC 110",
    category: "local-staples",
    desc: "Slow-simmered black-eyed beans in zesty zomi (palm oil), served with sweet fried plantains and garnished with gari.",
    img: "/Red Red (Gob3 Supreme).jfif",
    btn: "Order Now",
  },
];
